#!/bin/sh

apt-get update  -y # To get the latest package lists
apt-get upgrade -y # Installing the latest version of packages
apt-get install nmap -y # Install nmap

pip3 install dispy #Install dispy
pip3 install hashid #Install hashid

wget https://raw.githubusercontent.com/danielmiessler/SecLists/master/Passwords/Leaked-Databases/rockyou-20.txt # Collect default wordlist
wget https://raw.githubusercontent.com/Rednewspaper/The-Incredible-Machine/master/INCMACHINE0.0.5a.py?token=AOH75QGWF3LIWZDOXGFZBR26L6KYQ # Collect program, needs to be fixed when github page goes public
